apiVersion: apps/v1
kind: Deployment
metadata:
  name: namegen-app
  namespace: namegen
  labels:
    app: namegen
    component: application
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namegen
      component: application
  template:
    metadata:
      labels:
        app: namegen
        component: application
    spec:
      containers:
        - name: namegen-app
          image: roy3177/namegen:v3
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGODB_URL
            - name: SERVER_PORT
              value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
