apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: namegen
  labels:
    app: namegen
    component: database
spec:
  clusterIP: None
  selector:
    app: namegen
    component: database
  ports:
    - port: 27017
      targetPort: 27017
