apiVersion: v1
kind: Service
metadata:
  name: namegen-service
  namespace: namegen
  labels:
    app: namegen
    component: application
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: namegen
    component: application
  ports:
    - port: 80
      targetPort: 8080
